---
  - name: Install OpenMRS
    become: yes
    hosts: all
    vars:
      - odoo_git_repo_path: https://github.com/odoo/odoo.git 
    tasks:
      - name: update apt repo and cache
        apt:
          update_cache: yes

      - name: Clone a odoo repository
        ansible.builtin.git:
          repo: "{{ odoo_git_repo_path }}"
          dest: /home/devops/odoo
          clone: yes
          update: no

      - name: Install pip3
        ansible.builtin.apt:
          name: "{{ item }}"
          state: present
        with_items:
          - python3-pip
          - postgresql
          - postgresql-client

      - name: Create PostgreSQL user
        community.postgresql.postgresql_user:
          name: postgres
          password: postgres
          role_attr_flags: CREATEDB,SUPERUSER

      - name: Create a new database with name "postgressql"
        community.postgresql.postgresql_db:
          name: postgres

